// Export pages
export 'main/main_widget.dart' show MainWidget;
export 'adicionales/adicionales_widget.dart' show AdicionalesWidget;
export 'pizzas/pizzas_widget.dart' show PizzasWidget;
export 'clientes/clientes_widget.dart' show ClientesWidget;
export 'compravip/compravip_widget.dart' show CompravipWidget;
export 'empleados/empleados_widget.dart' show EmpleadosWidget;
export 'contacto/contacto_widget.dart' show ContactoWidget;
export 'pedido/pedido_widget.dart' show PedidoWidget;
export 'recoger/recoger_widget.dart' show RecogerWidget;
export 'domicilio/domicilio_widget.dart' show DomicilioWidget;
export 'iniciars/iniciars_widget.dart' show IniciarsWidget;
export 'isesion/isesion_widget.dart' show IsesionWidget;
export 'register1/register1_widget.dart' show Register1Widget;
export 'cuenta2/cuenta2_widget.dart' show Cuenta2Widget;
export 'soli/soli_widget.dart' show SoliWidget;
export 'coment/coment_widget.dart' show ComentWidget;
export 'cuentades/cuentades_widget.dart' show CuentadesWidget;
export 'conclusiones/conclusiones_widget.dart' show ConclusionesWidget;
